Changed: Project structure to support seperate tar files
The makedist utility, in conjuction with a .gitattributes file
will now generate both base project and meego branding release
tar balls.

These two tar balls can then be used as seperate sources for
package generation, since they are covered under different
licenses.

Signed-off-by: Shane Bryan <shane.bryan@linux.intel.com>

diff --git a/makedist b/makedist
--- a/makedist
+++ b/makedist
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 # Determine project name based on current directory
-PROJECT=$(basename $PWD)
+#PROJECT=$(basename $PWD)
+PROJECT="meego-handset-dialer"
 
 # NOTE: Don't like this?  Then uncomment one of the following as appropriate
 #
@@ -19,15 +20,34 @@ PARTS=(${TAG//-/ })
 VERSION=${PARTS[1]}
 
 # Set name of toplevel directory for the archive
-PREFIX="${PROJECT}-${VERSION}/"
+BASE_PREFIX="${PROJECT}-${VERSION}/"
+BRANDING_PREFIX="${PROJECT}-branding-meego-${VERSION}/"
 
 # Set name of resulting release archive file
-ARCHIVE=${PROJECT}-${VERSION}.tar.bz2
+BASE_ARCHIVE=${PROJECT}-${VERSION}.tar.bz2
+BRANDING_ARCHIVE=${PROJECT}-branding-meego-${VERSION}.tar.bz2
 
-[ -e ${ARCHIVE} ] && rm -rf ${ARCHIVE} && echo "Removed: ${ARCHIVE}"
+# Clean up any existing base package for this version
+[ -e ${BASE_ARCHIVE} ] && rm -rf ${BASE_ARCHIVE} &&
+	echo "Removed: ${BASE_ARCHIVE}"
 
-git archive --format=tar --prefix=${PREFIX} $TAG | bzip2 -c -- > ${ARCHIVE} && {
-	echo "Created: ${ARCHIVE}"
+# Generate the base package release tar ball
+# NOTE: Becuase I used a git attribute that ignores the meego theme dir
+#       this archive will not include it... that's intentional!
+git archive --prefix=${BASE_PREFIX} ${TAG} | bzip2 -c -- > ${BASE_ARCHIVE} && {
+	echo "Created: ${BASE_ARCHIVE}"
 } || {
-	echo "Creation of release archive ${ARCHIVE} failed.  Reason unknown."
+	echo "Creation of release archive ${BASE_ARCHIVE} failed.  Reason unknown."
 }
+
+# Clean up any existing branding package for this version
+[ -e ${BRANDING_ARCHIVE} ] && rm -rf ${BRANDING_ARCHIVE} &&
+	echo "Removed: ${BRANDING_ARCHIVE}"
+# Generate the branding package release tar ball
+pushd themes
+git archive --prefix=${BRANDING_PREFIX} ${TAG} meego/ themes.pro | bzip2 -c -- > ../${BRANDING_ARCHIVE} && {
+	echo "Created: ${BRANDING_ARCHIVE}"
+} || {
+	echo "Creation of release archive ${BRANDING_ARCHIVE} failed.  Reason unknown."
+}
+popd
