Added:   Update "Version:" key in .yaml file from mksnapshot script
Signed-off-by: Shane Bryan <shane.bryan@linux.intel.com>

diff --git a/mksnapshot b/mksnapshot
--- a/mksnapshot
+++ b/mksnapshot
@@ -19,6 +19,7 @@ git tag -l | grep $tag && {
 
 version=(${tag//./ })
 
+COMMIT_FILES="ChangeLog"
 
 # NOTE: Uses only first file that defines VERSION
 PRO_FILE=$(grep -El "VERSION ?= ?[0-9]+\.[0-9]+\.[0-9]+$" *.pr[io]|head -n1)
@@ -29,11 +30,22 @@ PRO_FILE=$(grep -El "VERSION ?= ?[0-9]+\.[0-9]+\.[0-9]+$" *.pr[io]|head -n1)
 		-e "s#_version_minor, [^)]*)#_version_minor, ${version[1]})#g" \
 		-e "s#_version_micro, [^)]*)#_version_micro, ${version[2]})#g" \
 		configure.ac
+	COMMIT_FILES="${COMMIT_FILES} configure.ac"
 } || {
 	# At least one .pro file exisits, modify VERSION tag in first .pro file
 	# TODO: fix this to be smarter than just modifying first .pro file
 	#       maybe looking for which one holds the VERSION tag?
 	sed -i	-e "s#VERSION = .*#VERSION = ${tag}#g" $PRO_FILE
+	COMMIT_FILES="${COMMIT_FILES} $PRO_FILE"
+}
+
+export $(grep -e "^PROJECT=\".*\"" makedist)
+YAML_FILE="${PROJECT//\"/}.yaml"
+[ "x$YAML_FILE" == "x" ] || {
+        # modify Version tag in the .yaml file to match the version we're
+        # tagging for this snapshot
+        sed -i -e "s#Version: .*#Version: ${tag}#g" $YAML_FILE
+	COMMIT_FILES="${COMMIT_FILES} $YAML_FILE"
 }
 
 echo -e "Changes in ${tag}\n" > ChangeLog.tmp &&
@@ -41,21 +53,10 @@ git log --pretty=oneline --abbrev=3 --abbrev-commit -r $(git describe --tags --a
 echo "" >> ChangeLog.tmp &&
 cat ChangeLog >> ChangeLog.tmp &&
 mv ChangeLog.tmp ChangeLog &&
-[ "x$PRO_FILE" == "x" ] && {
-	git commit -s ChangeLog configure.ac -m "Updated ChangeLog and configure.ac to version $tag" > /dev/null &&
-	git tag version-$tag && {
-		echo "Version set to $tag and tag laid."
-		echo "Make sure to 'git-push --tags' if you want to distribute."
-	} || {
-		echo "Version update failed.  Reason unknown.  Try git-diff."
-	}
+git commit -s $COMMIT_FILES -m "Updated release files to version $tag" > /dev/null &&
+git tag version-$tag && {
+	echo "Version set to $tag and tag laid."
+	echo "Make sure to 'git-push --tags' if you want to distribute."
 } || {
-	git commit -s ChangeLog $PRO_FILE -m "Updated ChangeLog and $PRO_FILE to version $tag" > /dev/null &&
-	git tag version-$tag && {
-		echo "Version set to $tag and tag laid."
-		echo "Make sure to 'git-push --tags' if you want to distribute."
-	} || {
-		echo "Version update failed.  Reason unknown.  Try git-diff."
-	}
+	echo "Version update failed.  Reason unknown.  Try git-diff."
 }
-
